class _LangEn {
    constructor() {
        this.arText = [];

        this.arText["title_game"] = "Find the ethereum"

        this.arText["address"] = "Address"
        this.arText["balance"] = "Balance"
        this.arText["bet"] = "Bet"
        this.arText["block"] = "block"
        this.arText["blocks"] = "blocks"
        this.arText["cashout"] = "Cashout"
        this.arText["close_channel"] = "Tokens are successfully distributed."
        this.arText["closed_dispute"] = "The dispute was successfully closed."
        this.arText["conflict_box"] = "Conflict box"
        this.arText["connecting"] = "Сonnecting"
        this.arText["congratulations"] = "Congratulations!"
        this.arText["continue"] = "Сontinue"
        this.arText["continue_game"] = "Place the prize and continue the game."
        this.arText["contract"] = "Contract"
        this.arText["contract_process"] = "SMART CONTRACT PROCESS"
        this.arText["disconnecting"] = "Disconnecting."
        this.arText["dispute_process"] = "The dispute will be closed on the contract through NUM blocks."
        this.arText["dispute_resolve"] = "The dispute will be settled on a smart contract."
        this.arText["dispute_close"] = "The dispute will soon be closed."
        this.arText["fullscreen"] = "Fullscreen"
        this.arText["history_game"] = "History game"
        this.arText["home"] = "Home"
        this.arText["instruction"] = "Instruction"
        this.arText["loading"] = "Loading"
        this.arText["lose"] = "LOSE"
        this.arText["new_game"] = "New game"
        this.arText["no"] = "No"
        this.arText["num"] = "Num"
        this.arText["open_channel_start"] = "Sending BETs into the game."
        this.arText["open_dispute"] = "Open dispute on the contract."
        this.arText["please_wait"] = "Please wait."
        this.arText["profit"] = "Profit"
        this.arText["reconnect_bankroll"] = "Reconnect bankroller"
        this.arText["save"] = "Save"
        this.arText["save_data"] = "Save data to the blockchain"
        this.arText["save_prize"] = "Save the profit and finish the game."
        this.arText["search_bankroller"] = "Search bankroller"
        this.arText["select_network"] = "Select network"
        this.arText["sending_dispute"] = "The dispute is open. Wait for the resolution of the dispute."
        this.arText["set_bet"] = "Select a bet SPL for the current game."
        this.arText["set_deposit"] = "Select the amount of BET SPL you are ready to play."
        this.arText["show_contract"] = "Show contract"
        this.arText["show_history"] = "Show history game"
        this.arText["site"] = "Site"
        this.arText["start"] = "START"
        this.arText["stay_in_the_game"] = "!!!STAY IN THE GAME!!!"
        this.arText["update_channel"] = "Update channel on contract"
        this.arText["update_game"] = "Update game on contract"
        this.arText["win"] = "WIN"
        this.arText["win_streak"] = "WIN STREAK"
        this.arText["win_streak2"] = "Win streak"
        this.arText["ws"] = "WS"
        this.arText["yes"] = "Yes"
        this.arText["your_bet"] = "YOUR BET"

        this.arText["desc_cashout"] = "Cashout tokens before closing the game"
        this.arText["desc_history_game"] = "Full history of all gaming sessions of the player"
        this.arText["desc_contract"] = "Smart contract on the blockchain"
        this.arText["desc_fullscreen"] = "Full screen mode"
        this.arText["desc_site"] = "Go to home page"

        this.arText["phrase_blockchain_1"] = "Wait, bankroller work"
        this.arText["phrase_blockchain_2"] = "Yes its not so fast"
        this.arText["phrase_blockchain_3"] = "This is Blockchain"
        this.arText["phrase_blockchain_4"] = "Transaction mining..."

        this.arText["error_account"] = "Account not initialized."
        this.arText["error_balance"] = "You do not have enough BET or ETH."
        this.arText["error_balance_bet"] = "You do not have enough BET."
        this.arText["error_balance_eth"] = "You do not have enough ETH."
        this.arText["error_balance_bankroll_bet"] = "Bankroller do not have enough BET. Try to choose a deposit less."
        this.arText["error_bankroll_offline"] = "Bankroller offline. Try later again."
        this.arText["error_bankroll_offline_to_arcade"] = "Bankroller offline or you have low balance. We transfer you to the arcade mode."
        this.arText["error_quick_return"] = "The previous session of the game is not closed. Try later (NUM min)."
        this.arText["error_address_contract"] = "You do not have the address of a smart contract."
        this.arText["invalid_data"] = "You sent invalid data."
        this.arText["invalid_signature_bankroll"] = "Bankroller did not sign the current event. We sent the dispute to smart contract ADR."
        this.arText["invalid_round_player"] = "The player sent the wrong round of the game."
        this.arText["invalid_signature_player"] = "Player did not sign the current event. We sent the dispute to smart contract ADR."
        this.arText["warning_game"] = "WARNING! Do not turn off the game, stay here."

        this.arText["tutor_1"] = "Hello! Choose your deposit and click ACCEPT."
        this.arText["tutor_2"] = "Now select a bet for one game."
        this.arText["tutor_3"] = "Good! Find the ethereum!"
        this.arText["tutor_4"] = "It is a pity that you lost, but you can play a new game."
        this.arText["tutor_5"] = "Make a decision and select the button."
    }

    getText(txt){
        return this.arText[txt] || txt
    }
}
const LangEn = new _LangEn();
export default LangEn;