version: "2.1"

networks:
  dc_network:
    driver: bridge

services:
  # ethereum test rpc network based on ganache-cli 
  dc_protocol:
    labels:
      - "TestRPC on port 1406"
      - "truffle ganache-cli"
    image:
      daocasino/protocol
    ports:
      - 1406:8545
    volumes:
      - ./protocol:/protocol
    networks:
       - dc_network
  
  # Bankroller node / casino backend
  # service watch dapp logic and reload node if his change 
  dc_bankroller:
    labels:
      - "dapp casino backend"
    depends_on:
      - dc_protocol
    image:
      daocasino/bankroller
    volumes:
      - ./protocol:/protocol
      - ./bankroller/dapps/:/bankroller/data_sdk/dapps/
      - ../build:/bankroller/data_sdk/dapps/sdk_dapp/
    entrypoint: 
      ["sh", "./run_sdk_env.sh"]
    networks:
      - dc_network
  dc_ipfs:
    image: ipfs/go-ipfs
    container_name: "ipfs_deployer"
    labels:
      - "IPFS node for Deploy DApp"
    volumes:
      - ../build:/go/target

